#!/bin/bash

source fs4git.sh

if [[ $# -eq 0 ]] ; then
    git add -A
elif [[ $# -ge 1 ]] ; then
    if isValidDate "$1" >/dev/null 2>&1 ; then
        export GIT_AUTHOR_DATE=$1
        export GIT_COMMITTER_DATE=$1
        git add -A
    else
        git add "$@" || exit 1 # file not exist
    fi
else
    printf "USAGE: git save [<date=now>] OR git save [<file(s)=all>]\n"
    exit 1
fi

git commit -S -s --reset-author --amend --no-edit &&\
printf "\n\n* * * LAST REVISION UPDATED * * *\n\n" &&\
git logs 1
