#!/bin/bash

source fs4git.sh

if [[ $# -eq 2 ]] ; then
    revision=$1
    message=$2
elif [[ $# -eq 3 ]] ; then
    revision=$1
    message=$2
    date=$3
else
    printf "USAGE: git rename <revision> <message> [<date=then>]\n"
    exit 1
fi

if [[ $revision -lt 1 || `totalNumberOfCommits HEAD` -le 1 || $revision -ge `totalNumberOfCommits HEAD` || `isInvalidDate "$date"` ]] ; then
    printf "USAGE: git rename <revision> <message> [<date=then>]\n"
    exit 1
fi

if [[ -z $date ]] ; then
    git join 1 "$message" $revision 2>&1 >/dev/null
else
    git join 1 "$message" $revision "$date" 2>&1 >/dev/null
fi &&\
printf "\n\n* * * #%d REVISION RENAMED AS \"%s\" * * *\n\n" $revision "$message" &&\
git logs $revision
