#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

. bash_template.sh
. fs4git.sh

SCRIPT_VERSION="1.1.0"
SCRIPT_DESCRIPTION="update current (or past) revision"
SCRIPT_FULL_DESCRIPTION="-"
SCRIPT_ARGUMENTS="[OPTION]... [FILE]..."
SCRIPT_OPTIONS=(\
    "--now"\
    "--then"\
    "-d DATE, --date=DATE"\
    "-m MESSAGE, --message=MESSAGE"\
    "-r REVISION, --revision=REVISION"\
    "-v, --verbose"\
    "--help"\
    "--version"\
)
SCRIPT_OPTION_DESCRIPTIONS=(\
    "current date"\
    "concerned revision date, default"\
    "date format is YYYY-mm-ddTHH:MM:SS"\
    ""\
    ""\
    "explain what is being done"\
    "display this help and exit"\
    "output version information and exit"\
)
SCRIPT_EXAMPLES=(\
    ""\
)
SCRIPT_SEE_ALSO=(\
    "git-join(1)"\
    "git-logs(1)"\
    "git-revision(1)"\
)

# # #   D E F A U L T   V A L U E S   # # #
if isGitRepo ; then
    originHash=$(commitHash HEAD)
    revision=$(commitHash HEAD)
    date=$(commitDate "${revision}")
    message=$(commitMessage "${revision}")
fi
# # #   E N D   # # # # # # # # # # # # # #

# We use "$@" instead of $* to preserve argument-boundary information
# Add : to suppress getopt error messages, i.e. getopt -o ':...'
ARGS=$(getopt -o 'd:m:r:v' --long 'now,then,date:,message:,revision:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
eval "set -- ${ARGS}"

while true; do
    case $1 in
        (--now)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            [[ ! -v isDateSet ]] || { error "date already selected" ; usage ; exit 1 ; }
            isDateSet= ; date=$(date +%Y-%m-%dT%H:%M:%S --date now) ; shift ;;
        (--then)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            [[ ! -v isDateSet ]] || { error "date already selected" ; usage ; exit 1 ; }
            isDateSet= ; shift ;;
        (-d|--date)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            [[ ! -v isDateSet ]] || { error "date already selected" ; usage ; exit 1 ; }
            isValidDate "$2" || { error "date format is YYYY-mm-ddTHH:MM:SS" ; usage ; exit 1 ; }
            isDateSet= ; date=$2 ; shift 2 ;;
        (-m|--message)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            isMessageSet= ; message=$2 ; shift 2 ;;
        (-r|--revision)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            isValidCommit "$2" || { error "revision does not exist" ; usage ; exit 1 ; }
            [[ -v isDateSet ]] || date=$(commitDate "$2")
            [[ -v isMessageSet ]] || message=$(commitMessage "$2")
            revision=$(commitHash "$2") ; shift 2 ;;
        (-v|--verbose)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            verbose= ; shift ;;
        (--help)
            usageFull ; exit 0 ;;
        (--version)
            about ; changelog ; exit 0 ;;
        (--update-manual) # hidden option
            updateManual ; exit 0 ;;
        (--)
            shift ; break ;;
        (*)
            usage ; exit 1 ;;
    esac
done

remainingArgs=("$@")

# # #   H E L P E R   F U N C T I O N S   # # #
originRevision() {
    git reflog | grep "${originHash:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }'
}
# # #   E N D   # # # # # # # # # # # # # # # #

main() {
    # errors=()

    if [[ ! -v verbose ]] ; then
        exec 3>&1 4>&2 1>/dev/null 2>&1
    fi

    local files
    files=("${remainingArgs[@]}")

    local updatedRevision
    updatedRevision=$(git logs --revision "${revision}")

    git join --verbose --date "${date}" --message "${message}" --from "${revision}" --to "$(commitHash "${revision}~1")" "${files[@]}" || { return 1 ; }

    if [[ ! -v verbose ]] ; then
        exec 1>&3 2>&4
    fi

    printf "%s\n" "${updatedRevision}"
    printf "* * * #%s REVISION UPDATED AS FOLLOWS * * *\n\n" "${revision:0:6}"
    git logs --revision "$(commitNumber "${revision}")"
}

recover() {
    printf "\n\n* * *   R E C O V E R (git-save)   * * *\n\n"

    # reset the index, but not the working tree (i.e. the changed files are preserved but not marked for commit)
    git reset "$(originRevision)" --

    if [[ ! -v verbose ]] ; then
        exec 1>&3 2>&4
    fi

    # for errorMsg in "${errors[@]}" ; do
    #     error "$errorMsg"
    # done
    error "recovered at ${originHash}" ; usage ; exit 1
}

trap recover SIGINT ERR && main
