#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

. bash_template.sh
. fs4git.sh

SCRIPT_VERSION="1.1.0"
SCRIPT_DESCRIPTION="show logs in custom format"
SCRIPT_FULL_DESCRIPTION="-"
SCRIPT_ARGUMENTS="[OPTION]... [FILE]..."
SCRIPT_OPTIONS=(\
    "-g, --graph"\
    "-r REVISION, --revision=REVISION"\
    "-G REGEX"\
    "-L START,END:FILE, -L :FUNCNAME:FILE"\
    "--help"\
    "--version"\
)
SCRIPT_OPTION_DESCRIPTIONS=(\
    "show graph of logs"\
    "show log with given hash or order number, the newest first"\
    ""\
    ""\
    "display this help and exit"\
    "output version information and exit"\
)
SCRIPT_EXAMPLES=(\
    ""\
)
SCRIPT_SEE_ALSO=(\
    "git-join(1)"\
    "git-revision(1)"\
    "git-save(1)"\
)

# # #   D E F A U L T   V A L U E S   # # #
if isGitRepo ; then
    originHash=$(commitHash HEAD)
    format="%C(yellow)%C(bold)%C(dim)%C(italic)%h%Creset %C(yellow)%C(bold)%s%Creset%n%C(cyan)%C(bold)%d%Creset %C(cyan)%cd (%cr) by %C(dim)%C(italic)%cn%Creset%n %C(cyan)%C(dim)%C(italic)%(trailers:key=Signed-off-by)%Creset"
fi
# # #   E N D   # # # # # # # # # # # # # #

# We use "$@" instead of $* to preserve argument-boundary information
# Add : to suppress getopt error messages, i.e. getopt -o ':...'
ARGS=$(getopt -o 'gr:G:L:' --long 'graph,revision:,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
eval "set -- ${ARGS}"

while true; do
    case $1 in
        (-g|--graph)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            graph= ; shift ;;
        (-r|--revision)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            isValidCommit "$2" || { error "revision does not exist" ; usage ; exit 1 ; }
            revision=$(commitHash "$2") ; shift 2 ;;
        (-G)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            regex=$2 ; shift 2 ;;
        (-L)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            L=$2 ; exit 2 ;;
        (--help)
            usageFull ; exit 0 ;;
        (--version)
            about ; changelog ; exit 0 ;;
        (--update-manual) # hidden option
            updateManual ; exit 0 ;;
        (--)
            shift ; break ;;
        (*)
            usage ; exit 1 ;;
    esac
done

remainingArgs=("$@")

# # #   H E L P E R   F U N C T I O N S   # # #
git-log() {
    git log --abbrev-commit --abbrev=12 --date=format:"%Y-%m-%d %H:%M:%S" "$@"
}
# # #   E N D   # # # # # # # # # # # # # # # #

main() {
    local files
    files=("${remainingArgs[@]}")

    if [[ -n ${graph+set} ]] ; then
        git log --all --graph --decorate --oneline
        exit 0
    fi

    if [[ -n ${revision-} ]] ; then
        git-log --pretty=format:"${format}" --max-count 1 "${revision}"
        printf "%s" "[${TERMINAL_DEFAULT_COLOR}m"
        exit 0
    fi

    if [[ -n ${regex-} ]] ; then
        printf "* * * MODIFIED BY THE FOLLOWING REVISION(S): * * *\n\n"
        git-log --pretty=format:"${format}" --all --full-history -G"${regex}" -- "${files[@]}"
        printf "%s" "[${TERMINAL_DEFAULT_COLOR}m"
        exit 0
    fi

    if [[ -n ${L-} ]] ; then
        printf "* * * MODIFIED BY THE FOLLOWING REVISION(S): * * *\n\n"
        git-log --pretty=format:"${format}" --reverse -L"${L}"
        printf "%s" "[${TERMINAL_DEFAULT_COLOR}m"
        exit 0
    fi

    if [[ -n ${files[0]-} ]] ; then
        printf "* * * MODIFIED BY THE FOLLOWING REVISION(S): * * *\n\n"
    fi

    git-log --pretty=format:"${format}" -- "${files[@]}"
    printf "%s" "[${TERMINAL_DEFAULT_COLOR}m"
}

recover() {
    printf "%s" "[${TERMINAL_DEFAULT_COLOR}m"
    error "recovered at ${originHash}" ; usage ; exit 1
}

trap recover SIGINT ERR && main
