#!/bin/bash

function getNumberOfCommits() {
    git rev-list --count $1
}

commits=$(getNumberOfCommits HEAD)
if [[ -z $1 || -z $2 || $1 -lt 1 || $commits -le 1 || $1 -ge $commits ]] ; then
    printf "USAGE: git rename <number> <message>\n"
    exit 1
fi

export number=$1 &&\
export hash=$( git rev-parse --short=6 HEAD~$(($number - 1)) ) &&\
export message=$2 &&\
#shift 2 &&\
git rebase HEAD~$number --exec 'if [[ $hash == $(git rev-parse --short=6 HEAD) ]] ; then git commit --amend -m $message ; fi' &&\
printf "\n\n* * * #%d REVISION RENAMED TO %s * * *\n\n" $number "\"$message\""
