#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

. bash_template.sh
. fs4git.sh

SCRIPT_VERSION="1.1.0"
SCRIPT_DESCRIPTION="create new revision"
SCRIPT_FULL_DESCRIPTION="-"
SCRIPT_ARGUMENTS="[OPTION]... MESSAGE [FILE]..."
SCRIPT_OPTIONS=(\
    "--amend"\
    "--no-auto-indexing"\
    "-d DATE, --date=DATE"\
    "-v, --verbose"\
    "--help"\
    "--version"\
)
SCRIPT_OPTION_DESCRIPTIONS=(\
    ""\
    ""\
    "date format is YYYY-mm-ddTHH:MM:SS"\
    "explain what is being done"\
    "display this help and exit"\
    "output version information and exit"\
)
SCRIPT_EXAMPLES=(\
    "MESSAGE"\
)
SCRIPT_SEE_ALSO=(\
    "git-join(1)"\
    "git-logs(1)"\
    "git-save(1)"\
)

# # #   D E F A U L T   V A L U E S   # # #
if isGitRepo ; then
    originHash=$(commitHash HEAD)
    all="--all"
    date=$(date +%Y-%m-%dT%H:%M:%S --date now)
fi
# # #   E N D   # # # # # # # # # # # # # #

# We use "$@" instead of $* to preserve argument-boundary information
# Add : to suppress getopt error messages, i.e. getopt -o ':...'
ARGS=$(getopt -o 'd:v' --long 'amend,no-auto-indexing,date:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
eval "set -- ${ARGS}"

while true; do
    case $1 in
        (--amend)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            amend="--reset-author --amend --no-edit" ; shift ;;
        (--no-auto-indexing)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            all= ; shift ;;
        (-d|--date)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            isValidDate "$2" || { error "date format is YYYY-mm-ddTHH:MM:SS" ; usage ; exit 1 ; }
            date=$2 ; shift 2 ;;
        (-v|--verbose)
            isGitRepo || { error "not a git repository" ; usage ; exit 1 ; }
            verbose= ; shift ;;
        (--help)
            usageFull ; exit 0 ;;
        (--version)
            about ; changelog ; exit 0 ;;
        (--update-manual) # hidden option
            updateManual ; exit 0 ;;
        (--)
            shift ; break ;;
        (*)
            usage ; exit 1 ;;
    esac
done

remainingArgs=("$@")

# # #   H E L P E R   F U N C T I O N S   # # #
originRevision() {
    git reflog | grep "${originHash:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }'
}
# # #   E N D   # # # # # # # # # # # # # # # #

main() {
    # errors=()

    if [[ ${#remainingArgs[@]} -lt 1 ]] ; then
        error "required parameters not supplied" ; usage ; exit 1
    fi

    if [[ ! -v verbose ]] ; then
        exec 3>&1 4>&2 1>/dev/null 2>&1
    fi

    local message files
    message=${remainingArgs[0]}
    files=("${remainingArgs[@]:1}")

    # shellcheck disable=SC2086
    git add ${all} -- "${files[@]}" || { return 1 ; }

    export GIT_AUTHOR_DATE=${date}
    export GIT_COMMITTER_DATE=${date}
    # shellcheck disable=SC2086
    git commit --gpg-sign --signoff --message "${message}" ${amend:=} -- || { return 1 ; }

    if [[ ! -v verbose ]] ; then
        exec 1>&3 2>&4
    fi

    printf "* * * NEW REVISION DONE * * *\n\n"
    git logs --revision HEAD
}

recover() {
    printf "\n\n* * *   R E C O V E R (git-revision)   * * *\n\n"

    export GIT_AUTHOR_DATE=
    export GIT_COMMITTER_DATE=

    # reset the index, but not the working tree (i.e. the changed files are preserved but not marked for commit)
    git reset "$(originRevision)" --

    if [[ ! -v verbose ]] ; then
        exec 1>&3 2>&4
    fi

    # for errorMsg in "${errors[@]}" ; do
    #     error "$errorMsg"
    # done
    error "recovered at ${originHash}" ; usage ; exit 1

}

trap recover SIGINT ERR && main
