#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

. bash_template.sh

SCRIPT_VERSION="1.0.0"
SCRIPT_DESCRIPTION="-"
SCRIPT_FULL_DESCRIPTION="-"
SCRIPT_ARGUMENTS="[OPTION]... FILE..."
SCRIPT_OPTIONS=(\
    "-o ORGANIZATION, --organization=ORGANIZATION"\
    "-v, --verbose"\
    "--help"\
    "--version"\
)
SCRIPT_OPTION_DESCRIPTIONS=(\
    "e.g. prutt21, intnet22"\
    "explain what is being done"\
    "display this help and exit"\
    "output version information and exit"\
)
SCRIPT_EXAMPLES=(\
    "--organization prutt21 groups"\
)
SCRIPT_SEE_ALSO=(\
    "gh-add-collaborators(1)"\
    "gh-clean-repos(1)"\
    "gh-init-repos(1)"\
    "gh-sort-groups(1)"\
)

# We use "$@" instead of $* to preserve argument-boundary information
# Add : to suppress getopt error messages, i.e. getopt -o ':...'
ARGS=$(getopt -o 'o:v' --long 'organization:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
eval "set -- ${ARGS}"

while true; do
    case $1 in
        (-o|--organization)
            ORGANIZATION=$2 ; shift 2 ;;
        (-v|--verbose)
            verbose= ; shift ;;
        (--help)
            usageFull ; exit 0 ;;
        (--version)
            about ; changelog ; exit 0 ;;
        (--update-manual) # hidden option
            updateManual ; exit 0 ;;
        (--)
            shift ; break ;;
        (*)
            usage ; exit 1 ;;
    esac
done

FILES=("$@")

[[ -v ORGANIZATION ]] || { error "required parameters not supplied" ; usage ; exit 1 ; } ;

# gh auth login --hostname "gits-15.sys.kth.se"

split() {
    local -n arr=$1
    local IFS="$2"; shift 2; read -ra arr <<< "$*"
}

while read -r line ; do
    declare -a STUDENTS
    split STUDENTS " " "${line}" # split by ' ' and uppdate STUDENTS : array

    for STUDENT in ${STUDENTS[@]} ; do
        gh api -X PUT "/orgs/${ORGANIZATION}/memberships/${STUDENT}" --silent || { printf "%s's membership not upgraded\n" "${STUDENT}"; }
    done

    # echo "${line}"
done < <(cat "${FILES[@]:--}") || true # or <(cat "$@" /dev/stdin)
