#!/bin/bash

FILE=$1 # kthids
ORGANIZATION=$2 # prutt21, intnet22

# gh auth login --hostname "gits-15.sys.kth.se"

join() {
    local -n str=$1
    local IFS="$2"; shift 2; str="$*";
}

split() {
    local -n arr=$1
    local IFS="$2"; shift 2; read -ra arr <<< "$*"
}

while read -r line ; do
    declare -a STUDENTS
    split STUDENTS " " "${line}" # split by ' ' and uppdate STUDENTS : array
    GROUP=
    join GROUP "-" "${STUDENTS[@]}" # join by '-' and update GROUP : string

    for STUDENT in ${STUDENTS[@]} ; do
        gh api -X PUT "/orgs/${ORGANIZATION}/memberships/${STUDENT}" --silent || { printf "%s's membership not upgraded\n" "${STUDENT}"; }
    done

    # echo "${line}"
done <"${FILE}"
